### ISSUE TITLE
Connect to sigfox backend

### ISSUE THREAD

**Issue by greg2891** [stm32duino/X-NUCLEO-S2868A2#3]
Hi 
Can anyone suggest how or add the option to connect to SigFox backend? 
As the board usually is registered with sigfox it would be helpfull to be able to see the hello world on sigfox backend - Thanks in advance

**Comment by cparata** [comment]
Hi @greg2891,
unfortunately, to use the hardware in a Sigfox network a proprietary code is needed. I do not have access at this code and I'm not expert on Sigfox network to help on this task.
Best Regards,
Carlo
